
<!DOCTYPE html>
<html>
    <head>
    <?php //This code is to go through the various databases and write the data onto the page via a table
            $currentrowtowrite = array();
            function tablerowwriter($array){
                for ($x = 0; $x <= sizeof($array); $x++) {
                    echo "<tr>" +$array[$x]+"</tr>";
                }
                echo "<br/>";
            }
            function dataloader($table){
                $servername = "localhost";
                $username = "id21488732_admin";
                $password = "Penispenis@@123";
                $dbname = "pathfinderdb";
                try{// Create connection
                    $conn = new mysqli($servername, $username, $password, $dbname);
                    if ($conn->connect_error) {
                    die("Connection failed: " . $conn->connect_error);
                    }
                    $sqlquery = "SELECT * FROM" + $table +"";
                }
                catch(Exception $e){
                    echo 'Caught exception: ',  $e->getMessage(), "\n";
                }
            }
        ?>
        <title>Pathfinder</title>
        <link rel="stylesheet" href="stylesheet.css">
        <script src="tripinitpageloader.js"></script>
        <link rel="icon" type="image" href="pathfindericon0.png">
        
    </head>
    <body>
        <nav class="mainnavbar"> <!--<ul><a class="mainnavbaritems"href=""></a></ul>-->
            <ul><a class="mainnavbaritems" href="index.html">Home</a></ul>
            <ul><a class="mainnavbaritems" href="tripitin.html">Trip Itinerary</a></ul>
            <ul><a class="mainnavbaritems" href="dest.html">Destination</a></ul>
            <ul><a class="mainnavbaritems" href="overdest.html">Overnight Destination</a></ul>
            <ul><a class="mainnavbaritems" href="activity.html">Activity</a></ul>
            <ul><a class="mainnavbaritems" href="trav.html">Travel</a></ul>
            <ul><a class="mainnavbaritems" href="test.html">Test</a></ul>
        </nav>
        <header>
            <h1>Trip Itinerary Review</h1>
        </header>
        <article> <!--Users -->
            <p>Below you can view you trip's itinerary: </p>
            <div class="autogentable" onload="dataloader()"> <!--This is the div hosting the table that is autogenerated, all elements would go in here-->
                <table>
                    
                    
                </table>
            </div>
        </article>
        <aside class="tripitin_left"><!--TODO: Style this to the left-->

        </aside>
        <aside class="tripitin_right"><!--TODO: Style this to the right-->

        </aside>
        <footer>
            <div class="footertext">
                <p>
                    <i>Created by CSC 4900 Group "Pathfinders". Fall 2023</i>
                </p>
            </div>
        </footer>
        
    </body>
    
</html>